# Generated by Django 4.1.3 on 2023-01-10 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('littleLemon', '0002_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='person_name',
        ),
    ]
