# Generated by Django 4.1.3 on 2023-01-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littleLemon', '0003_rename_name_person_person_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person_age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
