# Generated by Django 4.1.3 on 2023-01-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littleLemon', '0007_alter_menu_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('reservation_day', models.CharField(max_length=20)),
                ('seats', models.IntegerField()),
            ],
        ),
    ]
