# Generated by Django 4.1.3 on 2023-01-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littleLemon', '0008_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('time_log', models.TimeField(help_text='Enter the exact time!')),
            ],
        ),
    ]
